import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from '../users/user.entity';

@Injectable()
export class DatabaseMigrationsService implements OnModuleInit {
  constructor(
    @InjectRepository(User)
    private readonly usersRepository: Repository<User>,
  ) {}

  async onModuleInit() {
    await this.migrateSportTypes();
    await this.migrateTournamentFormats();
    await this.ensureTournamentDateColumns();
    await this.migrateTournamentStatuses();
    await this.ensureScoringRulesTable();
    await this.ensureStageNameConstraint();
    await this.ensureTeamPlayersTable();
    await this.cleanupLolUnknownTeams();
  }

  private async migrateSportTypes() {
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      DROP CONSTRAINT IF EXISTS chk_tournaments_sport_type
    `);
    await this.usersRepository.query(`
      UPDATE tournaments
      SET sport_type = CASE
        WHEN sport_type = 'ESPORTS' THEN 'LOL'
        WHEN sport_type = 'BASKETBALL' THEN 'OTHER'
        ELSE sport_type
      END
      WHERE sport_type IN ('ESPORTS', 'BASKETBALL')
    `);
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD CONSTRAINT chk_tournaments_sport_type
      CHECK (sport_type IN ('FOOTBALL', 'F1', 'LOL', 'OTHER'))
    `);
  }

  private async migrateTournamentFormats() {
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      DROP CONSTRAINT IF EXISTS chk_tournaments_format
    `);
    await this.usersRepository.query(`
      UPDATE tournaments
      SET format = 'ROUND_ROBIN'
      WHERE format IS NULL
         OR format NOT IN ('GROUP_AND_KNOCKOUT', 'ROUND_ROBIN', 'KNOCKOUT', 'CUSTOM')
    `);
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD CONSTRAINT chk_tournaments_format
      CHECK (format IN ('GROUP_AND_KNOCKOUT', 'ROUND_ROBIN', 'KNOCKOUT', 'CUSTOM'))
    `);
    await this.usersRepository.query(`
      CREATE TABLE IF NOT EXISTS tournament_custom_formats (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tournament_id INTEGER NOT NULL UNIQUE REFERENCES tournaments(id) ON DELETE CASCADE,
        name VARCHAR(255) NOT NULL,
        definition JSONB NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
  }

  private async ensureScoringRulesTable() {
    await this.usersRepository.query(`
      CREATE TABLE IF NOT EXISTS scoring_rules (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
        category VARCHAR(100) NOT NULL DEFAULT 'CUSTOM',
        title VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        points INTEGER NOT NULL DEFAULT 0,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_scoring_rules_points CHECK (points >= 0)
      )
    `);
    await this.usersRepository.query(`
      CREATE INDEX IF NOT EXISTS idx_scoring_rules_tournament
      ON scoring_rules(tournament_id, sort_order, id)
    `);
  }

  private async ensureStageNameConstraint() {
    await this.usersRepository.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_stages_tournament_name
      ON stages(tournament_id, LOWER(name))
    `);
  }

  private async ensureTournamentDateColumns() {
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ NULL
    `);
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD COLUMN IF NOT EXISTS end_date TIMESTAMPTZ NULL
    `);
    await this.usersRepository.query(`
      WITH match_ranges AS (
        SELECT
          tournament_id,
          MIN(scheduled_time) AS start_date,
          MAX(scheduled_time) AS end_date
        FROM matches
        GROUP BY tournament_id
      )
      UPDATE tournaments t
      SET
        start_date = COALESCE(t.start_date, match_ranges.start_date),
        end_date = COALESCE(t.end_date, match_ranges.end_date)
      FROM match_ranges
      WHERE match_ranges.tournament_id = t.id
        AND (t.start_date IS NULL OR t.end_date IS NULL)
    `);
    await this.usersRepository.query(`
      WITH football_api_match_ranges AS (
        SELECT
          m.tournament_id,
          MIN(m.scheduled_time) AS start_date,
          MAX(m.scheduled_time) AS end_date
        FROM matches m
        JOIN tournaments t ON t.id = m.tournament_id
        WHERE t.sport_type = 'FOOTBALL'
          AND m.external_source IN ('FOOTBALL_DATA', 'ESPN_ASEAN')
        GROUP BY m.tournament_id
      )
      UPDATE tournaments t
      SET
        start_date = football_api_match_ranges.start_date,
        end_date = football_api_match_ranges.end_date
      FROM football_api_match_ranges
      WHERE football_api_match_ranges.tournament_id = t.id
    `);
  }

  private async migrateTournamentStatuses() {
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      DROP CONSTRAINT IF EXISTS chk_tournaments_status
    `);
    await this.usersRepository.query(`
      DO $$
      DECLARE
        constraint_name TEXT;
      BEGIN
        FOR constraint_name IN
          SELECT con.conname
          FROM pg_constraint con
          JOIN pg_class rel ON rel.oid = con.conrelid
          JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
          WHERE rel.relname = 'tournaments'
            AND con.contype = 'c'
            AND pg_get_constraintdef(con.oid) ILIKE '%status%'
        LOOP
          EXECUTE format('ALTER TABLE tournaments DROP CONSTRAINT IF EXISTS %I', constraint_name);
        END LOOP;
      END $$;
    `);
    await this.usersRepository.query(`
      UPDATE tournaments
      SET status = CASE
        WHEN status IN ('ACTIVE', 'LIVE', 'ONGOING') THEN 'ONGOING'
        WHEN status IN ('COMPLETED', 'COMPLETE', 'FINISHED', 'CANCELLED', 'CANCELED') THEN 'COMPLETE'
        ELSE 'UPCOMING'
      END
      WHERE status IS NULL
         OR status NOT IN ('UPCOMING', 'ONGOING', 'COMPLETE')
    `);
    await this.usersRepository.query(`
      UPDATE tournaments
      SET status = CASE
        WHEN end_date IS NOT NULL AND end_date < NOW() THEN 'COMPLETE'
        WHEN start_date IS NOT NULL AND start_date > NOW() THEN 'UPCOMING'
        WHEN start_date IS NOT NULL AND start_date <= NOW()
          AND (end_date IS NULL OR end_date >= NOW()) THEN 'ONGOING'
        ELSE status
      END
    `);
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD CONSTRAINT chk_tournaments_status
      CHECK (status IN ('UPCOMING', 'ONGOING', 'COMPLETE'))
    `);
  }

  private async cleanupLolUnknownTeams() {
    const unknownNames = ['tbd', 'team 1', 'team 2', 'home team', 'away team'];

    await this.usersRepository.query(
      `
        DELETE FROM matches m
        USING tournaments t
        WHERE t.id = m.tournament_id
          AND t.sport_type = 'LOL'
          AND COALESCE(m.external_source, 'MANUAL') = 'CITO_LOL'
          AND (
            LOWER(TRIM(COALESCE((SELECT home.name FROM teams home WHERE home.id = m.home_team_id), m.home_placeholder, ''))) = ANY($1)
            OR LOWER(TRIM(COALESCE((SELECT away.name FROM teams away WHERE away.id = m.away_team_id), m.away_placeholder, ''))) = ANY($1)
          )
      `,
      [unknownNames],
    );

    await this.usersRepository.query(
      `
        DELETE FROM teams team
        USING tournaments t
        WHERE t.id = team.tournament_id
          AND t.sport_type = 'LOL'
          AND LOWER(TRIM(team.name)) = ANY($1)
      `,
      [unknownNames],
    );
  }

  private async ensureTeamPlayersTable() {
    await this.usersRepository.query(`
      CREATE TABLE IF NOT EXISTS team_players (
        id SERIAL PRIMARY KEY,
        team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
        name VARCHAR(120) NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    await this.usersRepository.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_team_players_team_name
      ON team_players(team_id, LOWER(name))
    `);
  }
}
