import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from '../users/user.entity';

@Injectable()
export class DatabaseMigrationsService implements OnModuleInit {
  constructor(
    @InjectRepository(User)
    private readonly usersRepository: Repository<User>,
  ) {}

  async onModuleInit() {
    await this.migrateSportTypes();
    await this.ensureScoringRulesTable();
    await this.ensureStageNameConstraint();
  }

  private async migrateSportTypes() {
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      DROP CONSTRAINT IF EXISTS chk_tournaments_sport_type
    `);
    await this.usersRepository.query(`
      UPDATE tournaments
      SET sport_type = CASE
        WHEN sport_type = 'ESPORTS' THEN 'LOL'
        WHEN sport_type = 'BASKETBALL' THEN 'OTHER'
        ELSE sport_type
      END
      WHERE sport_type IN ('ESPORTS', 'BASKETBALL')
    `);
    await this.usersRepository.query(`
      ALTER TABLE tournaments
      ADD CONSTRAINT chk_tournaments_sport_type
      CHECK (sport_type IN ('FOOTBALL', 'F1', 'LOL', 'OTHER'))
    `);
  }

  private async ensureScoringRulesTable() {
    await this.usersRepository.query(`
      CREATE TABLE IF NOT EXISTS scoring_rules (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
        category VARCHAR(100) NOT NULL DEFAULT 'CUSTOM',
        title VARCHAR(255) NOT NULL,
        content TEXT NOT NULL,
        points INTEGER NOT NULL DEFAULT 0,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT chk_scoring_rules_points CHECK (points >= 0)
      )
    `);
    await this.usersRepository.query(`
      CREATE INDEX IF NOT EXISTS idx_scoring_rules_tournament
      ON scoring_rules(tournament_id, sort_order, id)
    `);
  }

  private async ensureStageNameConstraint() {
    await this.usersRepository.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_stages_tournament_name
      ON stages(tournament_id, LOWER(name))
    `);
  }
}
